name: Build libimobiledevice (skip cython)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # 这里可以根据需要添加更多版本或架构

    env:
      LIBPLIST_VERSION: 2.7.0
      LIBUSBMUXD_VERSION: 2.1.0
      LIBIMOBILEDEVICE_VERSION: 1.3.0

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool pkg-config gettext curl

    - name: Install dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install autoconf automake libtool pkg-config gettext curl

    - name: Install dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install -y msys2
        echo "Ensure your MSYS2 environment is setup and packages like make, gcc, pkg-config are available"

    - name: Download dependency source tarballs
      run: |
        wget -O libplist-${{ env.LIBPLIST_VERSION }}.tar.gz https://github.com/libimobiledevice/libplist/archive/refs/tags/${{ env.LIBPLIST_VERSION }}.tar.gz
        wget -O libusbmuxd-${{ env.LIBUSBMUXD_VERSION }}.tar.gz https://github.com/libimobiledevice/libusbmuxd/archive/refs/tags/${{ env.LIBUSBMUXD_VERSION }}.tar.gz
        wget -O libimobiledevice-${{ env.LIBIMOBILEDEVICE_VERSION }}.tar.gz https://github.com/libimobiledevice/libimobiledevice/archive/refs/tags/${{ env.LIBIMOBILEDEVICE_VERSION }}.tar.gz

    - name: Extract dependency sources
      run: |
        tar -xzf libplist-${{ env.LIBPLIST_VERSION }}.tar.gz
        tar -xzf libusbmuxd-${{ env.LIBUSBMUXD_VERSION }}.tar.gz
        tar -xzf libimobiledevice-${{ env.LIBIMOBILEDEVICE_VERSION }}.tar.gz

    - name: Build and install libplist
      run: |
        cd libplist-${{ env.LIBPLIST_VERSION }}
        ./autogen.sh --prefix=$HOME/.local
        make
        make install

    - name: Build and install libusbmuxd
      run: |
        cd libusbmuxd-${{ env.LIBUSBMUXD_VERSION }}
        ./autogen.sh --prefix=$HOME/.local PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig
        make
        make install

    - name: Build libimobiledevice (skip cython)
      run: |
        cd libimobiledevice-${{ env.LIBIMOBILEDEVICE_VERSION }}
        ./autogen.sh --prefix=$HOME/.local PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig
        make
        make install

    - name: Package binaries
      run: |
        mkdir -p release_bin
        # 这里示例只拷贝一个二进制文件，请根据需要调整
        cp $HOME/.local/bin/ideviceinstaller release_bin/
        ls -lh release_bin

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: release_bin/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
