name: build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            autoconf automake libtool \
            libimobiledevice-glue-dev libplist-dev \
            libusbmuxd-dev libssl-dev \
            libzip-dev make gcc pkg-config tar
      - name: Build
        run: |
          ./autogen.sh --without-cython
          make -j$(nproc)
          make install DESTDIR=$PWD/dest
          tar -C dest -cf libimobiledevice-linux.tar usr
      - name: Upload Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly-${{ github.run_number }}
          name: Nightly Build ${{ github.run_number }}
          files: libimobiledevice-linux.tar

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install autoconf automake libtool libzip openssl libplist libusbmuxd
      - name: Build
        run: |
          export LDFLAGS="-L/opt/homebrew/lib"
          export CPPFLAGS="-I/opt/homebrew/include"
          ./autogen.sh --without-cython
          make -j$(sysctl -n hw.ncpu)
          make install DESTDIR=$PWD/dest
          tar -C dest -cf libimobiledevice-macos.tar usr
      - name: Upload Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly-${{ github.run_number }}
          name: Nightly Build ${{ github.run_number }}
          files: libimobiledevice-macos.tar

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          choco install -y msys2
      - name: Build
        shell: msys2 {0}
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm \
            autoconf automake libtool pkg-config make tar \
            mingw-w64-${{ matrix.arch }}-gcc \
            mingw-w64-${{ matrix.arch }}-libimobiledevice-glue \
            mingw-w64-${{ matrix.arch }}-libplist \
            mingw-w64-${{ matrix.arch }}-libusbmuxd \
            mingw-w64-${{ matrix.arch }}-openssl \
            mingw-w64-${{ matrix.arch }}-libzip
          export PATH="/mingw64/bin:$PATH"
          ./autogen.sh --without-cython
          make -j$(nproc)
          make install DESTDIR=$PWD/dest
          tar -C dest -cf libimobiledevice-windows-${{ matrix.arch }}.tar usr
      - name: Upload Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly-${{ github.run_number }}
          name: Nightly Build ${{ github.run_number }}
          files: libimobiledevice-windows-${{ matrix.arch }}.tar
