name: Build libimobiledevice Windows

on:
  push:
    branches:
      - master
  tags:
    - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install MSYS2 and dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-gcc 
            mingw-w64-x86_64-make 
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-libplist
            mingw-w64-x86_64-usbmuxd
            mingw-w64-x86_64-libusb

      - name: Configure and build libimobiledevice
        shell: bash
        run: |
          ./autogen.sh --host=x86_64-w64-mingw32 --prefix=/mingw64
          make -j$(nproc)
          make install

      - name: Collect binaries
        run: |
          mkdir output
          cp /mingw64/bin/ideviceinfo.exe ./output/
          cp /mingw64/bin/ideviceinstaller.exe ./output/ || true
          # 复制其它你需要的exe和dll

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
